### ISSUE TITLE
Blender 2.8 BETA date 25.01.

### ISSUE THREAD

**Issue by Tweinek** [kevancress/sun_position_b28_test#1]
First of all - Thank you very much Kevan for this addon. 

When I press Enable buton:
1. Options disappear.
2. Click in viewport gives information like this:
```
"Traceback (most recent call last):
  File "C:\Users\Paweł_2\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 118, in draw
    self.disable(context, layout)
  File "C:\Users\Paweł_2\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 45, in disable
    Map.zoom_preferences(bpy.context.user_preferences.inputs.invert_zoom_wheel,
AttributeError: 'Context' object has no attribute 'user_preferences'

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Paweł_2\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 118, in draw
    self.disable(context, layout)
  File "C:\Users\Paweł_2\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 45, in disable
    Map.zoom_preferences(bpy.context.user_preferences.inputs.invert_zoom_wheel,
AttributeError: 'Context' object has no attribute 'user_preferences'

location: <unknown location>:-1
```

"

**Comment by Tweinek** [comment]
Help came from @Peetie at https://www.blendernation.com/

He wrote: "You can get the addon to work (if there are no other issues in the addon) by finding in the code all lines that have;
bpy.context.user_preferences
Change that into:
bpy.context.preferences"

and that works.

**Comment by Tweinek** [comment]
Further options are broken. Sun doesn't move at all.

**Comment by kevancress** [comment]
Hey Tweinek, thanks for testing!

Looks like the issue had to do with a change in how values are returned from prop_search (https://developer.blender.org/T59106).

Should be working now.
