### ISSUE TITLE
Error to activate the add-on Blender 2.80 & macOS

### ISSUE THREAD

**Issue by Oxervision** [kevancress/sun_position_b28_test#2]
Hi,
I installed the last version (3.0.1) of Sun Position 2.8 and when I try to activate it appears this message error:
```
Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/sun_position_b28_test-master/__init__.py", line 49, in <module>
    from . ui_sun import *
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/sun_position_b28_test-master/ui_sun.py", line 5, in <module>
    from . operators import *
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/sun_position_b28_test-master/operators.py", line 6, in <module>
    from . north import *
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/sun_position_b28_test-master/north.py", line 10, in <module>
    dashedLineShader = gpu.types.GPUShader(Dashed_Shader_3D.vertex_shader, Dashed_Shader_3D.fragment_shader)
Exception: Shader Compile Error, see console for more details

```
The Blender 2.8's API had just changed again, causing many add-ons not to work anymore.

Many thanks in advance for fixing it.

Regards,

Óscar

**Comment by kevancress** [comment]
Hi Oxervision, Thanks for reporting,

I've just pushed a commit that should fix the Shader Compile Error you're experiencing, give it a shot and let me know if things are working for you!

**Comment by Oxervision** [comment]
The add-on works fine now but the World Map doesn't show (Panel or Viewport).
If you press _Toggle day or (month / day) range_ button, the icon button will disappear and you will not be able to return to the previous option.
