### ISSUE TITLE
error in gui blender 2.8 rc3

### ISSUE THREAD

**Issue by frankyifei** [kevancress/sun_position_b28_test#3]
was working normally. suddenly the panel does not show up. check console window, 
`Traceback (most recent call last):
  File "C:\Users\f\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 118, in draw
    self.disable(context, layout)
  File "C:\Users\f\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sun_position_b28_test-master\ui_sun.py", line 45, in disable
    Map.zoom_preferences(bpy.context.user_preferences.inputs.invert_zoom_wheel,
AttributeError: 'Context' object has no attribute 'user_preferences'`

**Comment by frankyifei** [comment]
I did not change the file but edit attribute back to "preferences" should work
